# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.


[[main]]
name = "Blog"
pageRef = "posts"
weight = 20

[[main]]
name = "Projects"
pageRef = "projects"
weight = 30

[[main]]
name = "Hobbies"
pageRef = "hobbies"
weight = 40


[[main]]
name = "Overview"
parent = "About"
pageRef = "about"
weight = 50

[[main]]
name = "Resume"
parent = "About"
url = "/resume.pdf"
weight = 55


[[main]]
name = "Resources"
parent = "Other"
pageRef = "resources"
weight = 70

[[main]]
name = "Product reviews"
parent = "Other"
pageRef = "product-reviews"
weight = 75

# [[main]]
# name = "About"
# pageRef = "about"
# weight = 50

# [[main]]
# pre = "github"
# name = ""
# identifier = "GitHub"
# title = "GitHub"
# url = "https://github.com/jhrcook"
# weight = 100

# [[main]]
# pre = "mug-hot"
# identifier = "Buy Me a Coffee"
# name = ""
# title = "Buy Me a Coffee"
# url = "https://www.buymeacoffee.com/joshuacook"
# weight = 110

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


[[footer]]
name = "Tags"
pageRef = "tags"
weight = 10

[[footer]]
name = "Categories"
pageRef = "categories"
weight = 20
